config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    resources :course_groups do
      member do
        post 'registrate'
        post 'deregistrate'
        post 'update_grades'
      end
    end
  end
  get 'course_groups/overview' => 'course_groups#overview'

  resources :field_of_studies do
    resources :semesters do
      post 'add_students', on: :member
      delete 'remove_students', on: :member
    end
  end
  resources :registrations

  get 'select_users' => 'modals#select_users', as: :select_users_modal
  get 'update_grades' => 'modals#update_grades', as: :update_grades_modal
  get 'add_students' => 'modals#add_students', as: :add_students_modal

  root 'dashboard#index'
  get 'my_study' => 'users#my_study', as: :my_study_user

  devise_for :users, skip: [:registrations]

  get 'language' => 'languages#change', as: :change_language

  resources :users do
    patch 'update_password', on: :member
  end

  get 'edit_account' => 'users#edit_account'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/models/semester.rb
# == Schema Information
#
# Table name: semesters
#
#  id                :integer          not null, primary key
#  field_of_study_id :integer
#  start_date        :datetime
#  end_date          :datetime
#  period_type       :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Semester < ActiveRecord::Base
  belongs_to :field_of_study
  has_many :subjects, dependent: :destroy
  has_many :registrations
  has_and_belongs_to_many :users

  validates :field_of_study, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  def to_s
    "#{field_of_study.title} #{start_date.year}/#{end_date.year}"
  end

  def students
    users.where(role: 'Student')
  end
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_action :set_field_of_study_and_semester, only: %i[show edit update destroy add_students remove_students]

  def index
    @field_of_study = FieldOfStudy.find params[:field_of_study_id]
    @semesters = @field_of_study.semesters
  end

  def show
    authorize @semester
  end

  def new
    @field_of_study = FieldOfStudy.find params[:field_of_study_id]
    @semester = Semester.new
    authorize @semester
  end

  def edit
    authorize @semester
  end

  def create
    @semester = Semester.new(semester_params)
    authorize @semester

    respond_to do |format|
      if @semester.save
        format.html { redirect_to field_of_study_semesters_path(@semester.field_of_study_id) }
      else
        format.html { render :new }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @semester

    respond_to do |format|
      if @semester.update(semester_params)
        format.html { redirect_to field_of_study_semesters_path(@semester.field_of_study_id) }
      else
        format.html { render :edit }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @semester

    @semester.destroy
    respond_to do |format|
      format.html { redirect_to field_of_study_semesters_path(@semester.field_of_study_id) }
    end
  end

  def add_students
    authorize @semester

    if params[:student_ids]
      students = Student.find params[:student_ids]
      SemesterJoiner.new(@semester).join(students)
    end
    redirect_to action: 'show', field_of_study: params[:field_of_study], id: params[:id]
  end

  def remove_students
    authorize @semester

    if params[:student_ids]
      students = Student.find params[:student_ids]
      SemesterJoiner.new(@semester).leave(students)
    end
    redirect_to action: 'show', field_of_study: params[:field_of_study], id: params[:id]
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_field_of_study_and_semester
    @field_of_study = FieldOfStudy.find params[:field_of_study_id]
    @semester = Semester.find params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def semester_params
    params.require(:semester).permit(:start_date, :end_date, :period_type, :field_of_study_id, :student_ids)
  end
end

app/views/semesters/_form.html.haml
= simple_form_for([@field_of_study, @semester]) do |f|
  = f.error_notification

  .form-inputs
    .row
      .col-md-6.col-md-offset-3
        = f.input :start_date
      .col-md-6.col-md-offset-3
        = f.input :end_date
    .row
      .col-md-6.col-md-offset-3
        = f.association :field_of_study, include_blank: false, selected: @field_of_study.id
  .row
    .col-md-12
      .last-element.text-center
        = link_to t('.cancel'), field_of_study_semesters_path, class: 'btn btn-default'
        = f.submit t('.save'), class: 'btn btn-info'

app/views/semesters/edit.html.haml
.row
  .col-md-8.col-md-offset-2
    %h3.page-header.text-center= @semester
    = render 'form'

app/views/semesters/index.html.haml
%h3.page-header
  = t('.semesters')
  %small= @field_of_study.title

- if @semesters.any?
  .row
    .col-md-12
      %table.table
        %thead
          %tr
            %th= t('.semester')
            %th= t('.associated_subjects')
            %th= t('.registrated_users')
            - if policy(:semester).show?
              %th
            - if policy(:semester).edit?
              %th
            - if policy(:semester).destroy?
              %th

        %tbody
          - @semesters.each do |semester|
            %tr
              %td
                %strong= semester
              %th= semester.subjects.count
              %td= semester.users.count
              - if policy(:semester).show?
                %td= link_to t('.details'), field_of_study_semester_path(@field_of_study, semester)
              - if policy(:semester).edit?
                %td= link_to t('.edit'), edit_field_of_study_semester_path(@field_of_study, semester)
              - if policy(:semester).destroy?
                %td
                  = link_to field_of_study_semester_path(@field_of_study, semester), method: :delete, :data => { :confirm => "Are you sure?" } do
                    %span.glyphicon.glyphicon-trash{'aria-hidden'=>"true"}
- else
  %p= t('.no_semesters_message')
.row
  .col-md-12
    - if policy(:semester).new?
      = link_to t('.new_semester'), new_field_of_study_semester_path(@field_of_study), class: 'btn btn-primary last-element'

app/views/semesters/new.html.haml
.row
  .col-md-8.col-md-offset-2
    %h3.page-header.text-center= t('.add_new_semester')
    = render 'form'

app/views/semesters/semesters.html.haml
%h3.page-header
  = t('.semesters')
  %small= @field_of_study.title

- if @semesters.any?
  .row
    .col-md-12
      %table.table
        %thead
          %tr
            %th= t('.semester')
            %th= t('.description')
            %th
            - if policy(:semester).edit?
              %th
            %th
            - if policy(:semester).destroy?
              %th

        %tbody
          - semesters.each do |semester|
            %tr
              %td
                %strong= semester.title
              %td.description= semester.description
              %td= link_to t('.show'), semester
              - if policy(:semester).edit?
                %td= link_to t('.edit'), edit_semester_path(semester)
              %td= link_to t('.groups'), semester_course_groups_path(semester.id)
              - if policy(:semester).destroy?
                %td
                  = link_to semester_path(semester), method: :delete, :data => { :confirm => "Are you sure?" } do
                    %span.glyphicon.glyphicon-trash{'aria-hidden'=>"true"}
- else
  %p= t('.no_subjects_message')

app/views/semesters/show.html.haml
.row
  .col-md-10.col-md-offset-1
    .panel.panel-default
      .panel-heading
        %h4= @semester
      .panel-body
        %p
          %strong= t('.mode') + ':'
          %span= t("field_of_studies.mode_types.#{@field_of_study.mode}")
        %p
          %strong= t('.degree') + ':'
          %span= t("field_of_studies.degree_types.#{@field_of_study.degree}")
        %p
          %strong= t('.faculty') + ':'
          %span= @field_of_study.faculty.name

        %hr
        .row
          .col-md-6
            .row
              .col-md-12
                %h5.mg-b-0.show-semester-table-header
                  = t('.subjects')
                  %small= "(#{@semester.subjects.count})"
            - if @semester.subjects.any?
              %table.table
                %thead
                  %tr
                    %th
                    %th

                %tbody
                  - @semester.subjects.each do |subject|
                    %tr
                      %td= subject.title
                      %td= link_to t(".details"), subject_path(subject)
          .col-md-6.modal_button_parent
            .row
              .col-md-8
                %h5.mg-b-0.show-semester-table-header
                  = t('.users')
                  %small= "(#{@semester.users.count})"
              - if policy(:semester).add_students?
                .col-md-4
                  %button#show_modal.btn.btn-success.pull-right{data: {modal: 'add_students', url: add_students_modal_path(semester_id: @semester.id) } }
                    = t('.add_students')
            - if @semester.students.any?
              %table.table
                %thead
                  %tr
                    %th
                    %th
                    - if policy(:semester).remove_students?
                      %th

                %tbody
                  - @semester.students.each do |user|
                    %tr
                      %td= user.name
                      %td= link_to t(".details"), user_path(user)
                      - if policy(:semester).remove_students?
                        %td
                          = link_to remove_students_field_of_study_semester_path(field_of_study_id: @field_of_study.id, id: @semester.id, student_ids: user.id), method: :delete, :data => { :confirm => "Are you sure?" } do
                            %span.glyphicon.glyphicon-remove{"data-toggle" =>"tooltip", "data-placement" => 'top', "title" => t(".info_message")}


.row
  .col-md-10.col-md-offset-1
    = link_to t('.back'), field_of_study_semesters_path(@field_of_study), class: 'btn btn-default last-element'

#modal_placeholder