config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    resources :course_groups do
      member do
        post 'registrate'
        post 'deregistrate'
        post 'update_grades'
      end
    end
  end
  get 'course_groups/overview' => 'course_groups#overview'

  resources :field_of_studies do
    resources :semesters do
      post 'add_students', on: :member
      delete 'remove_students', on: :member
    end
  end
  resources :registrations

  get 'select_users' => 'modals#select_users', as: :select_users_modal
  get 'update_grades' => 'modals#update_grades', as: :update_grades_modal
  get 'add_students' => 'modals#add_students', as: :add_students_modal

  root 'dashboard#index'
  get 'my_study' => 'users#my_study', as: :my_study_user

  devise_for :users, skip: [:registrations]

  get 'language' => 'languages#change', as: :change_language

  resources :users do
    patch 'update_password', on: :member
  end

  get 'edit_account' => 'users#edit_account'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id                :integer          not null, primary key
#  title             :string
#  coordinator_id    :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  description       :text
#  short_description :text
#  literature        :text
#  requirements      :text
#  learning_outcomes :text
#  semester_id       :integer
#

class Subject < ActiveRecord::Base
  has_many :course_groups, dependent: :destroy
  belongs_to :semester

  validates :semester, presence: true
  validates :title, :short_description, presence: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[show edit update destroy]

  def index
    authorize Semester
    @semesters = policy_scope(Semester)
  end

  def new
    @subject = Subject.new
    authorize @subject
  end

  def create
    @subject = Subject.new(subject_params)
    authorize @subject

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subjects_path, notice: 'subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def show; end

  def edit
    authorize @subject
  end

  def update
    authorize @subject
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @subject

    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_path }
      # format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @subject = Subject.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def subject_params
    params.require(:subject)
          .permit(
            :title,
            :description,
            :short_description,
            :literature,
            :requirements,
            :learning_outcomes,
            :semester_id
          )
  end
end

app/views/subjects/_form.html.haml
= simple_form_for(@subject, html: {class: 'form', role: "form"} ) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, label: t('.title')
    = f.input :short_description, label: t('.short_description'), as: :text, input_html: {rows: 2}
    = f.input :description, label: t('.description'), as: :text, input_html: {rows: 4}
    = f.input :requirements, label: t('.requirements'), as: :text, input_html: {rows: 4}
    = f.input :learning_outcomes, label: t('.learning_outcomes'), as: :text, input_html: {rows: 4}
    = f.input :literature, label: t('.literature'), as: :text, input_html: {rows: 4}
    = f.association :semester, label: t('.semester'), include_blank: false

  .row
    .col-md-12
      .pull-right.last-element
        = link_to t('.cancel'), subjects_path, class: 'btn btn-default'
        = f.submit t('.save'), class: 'btn btn-info'

app/views/subjects/edit.html.haml
.row
  .col-md-8.col-md-offset-2
    %h3.page-header= @subject.title
    = render 'form'

app/views/subjects/index.html.haml
%h3.page-header= t(".subjects")

- @semesters.order(:field_of_study_id).each do |semester|
  %h4
    %span= semester
    %span.glyphicon.glyphicon-menu-down.hoverable{data: {toggle: :collapse, target: "#semester_#{semester.id}"}}
  - if semester.subjects.any?
    .row.collapse.in.fold{id: "semester_#{semester.id}"}
      .col-md-12
        %table.table
          %thead
            %tr
              %th= t('.title')
              %th= t('.description')
              %th
              - if policy(:subject).edit?
                %th
              %th
              - if policy(:subject).destroy?
                %th

          %tbody
            - semester.subjects.order(:title).each do |subject|
              %tr
                %td
                  %strong= subject.title
                %td.description= subject.description
                %td= link_to t('.show'), subject
                - if policy(:subject).edit?
                  %td= link_to t('.edit'), edit_subject_path(subject)
                %td= link_to t('.groups'), subject_course_groups_path(subject.id)
                - if policy(:subject).destroy?
                  %td
                    = link_to subject_path(subject), method: :delete, :data => { :confirm => "Are you sure?" } do
                      %span.glyphicon.glyphicon-trash{'aria-hidden'=>"true"}
  - else
    %p= t('.no_subjects_message')

%br

- if policy(:subject).new?
  = link_to t('.add_new'), new_subject_path, class: 'btn btn-primary last-element'
= link_to t('.course_groups'), course_groups_overview_path, class: 'pull-right'

app/views/subjects/new.html.haml
.row
  .col-md-8.col-md-offset-2
    %h3.page-header= t('.add_new_subject')
    = render 'form'

app/views/subjects/show.html.haml
.row
  .col-md-8.col-md-offset-2
    %h3.page-header
      = @subject.title
      %small= @subject.semester
.row
  .col-md-8.col-md-offset-2
    - %w(short_description description requirements learning_outcomes literature).each do |attribute|
      %h5= t(".#{attribute}")
      %p= @subject[attribute]
.row
  .col-md-8.col-md-offset-2
    = link_to t('.back'), subjects_path, class: 'btn btn-default'
    = link_to t('.course_groups'), subject_course_groups_path(@subject), class: 'btn btn-info pull-right last-element'