config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    resources :course_groups do
      member do
        post 'registrate'
        post 'deregistrate'
        post 'update_grades'
      end
    end
  end
  get 'course_groups/overview' => 'course_groups#overview'

  resources :field_of_studies do
    resources :semesters do
      post 'add_students', on: :member
      delete 'remove_students', on: :member
    end
  end
  resources :registrations

  get 'select_users' => 'modals#select_users', as: :select_users_modal
  get 'update_grades' => 'modals#update_grades', as: :update_grades_modal
  get 'add_students' => 'modals#add_students', as: :add_students_modal

  root 'dashboard#index'
  get 'my_study' => 'users#my_study', as: :my_study_user

  devise_for :users, skip: [:registrations]

  get 'language' => 'languages#change', as: :change_language

  resources :users do
    patch 'update_password', on: :member
  end

  get 'edit_account' => 'users#edit_account'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/models/semester.rb
# == Schema Information
#
# Table name: semesters
#
#  id                :integer          not null, primary key
#  field_of_study_id :integer
#  start_date        :datetime
#  end_date          :datetime
#  period_type       :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Semester < ActiveRecord::Base
  belongs_to :field_of_study
  has_many :subjects, dependent: :destroy
  has_many :registrations
  has_and_belongs_to_many :users

  validates :field_of_study, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  def to_s
    "#{field_of_study.title} #{start_date.year}/#{end_date.year}"
  end

  def students
    users.where(role: 'Student')
  end
end

app/controllers/modals_controller.rb
class ModalsController < ApplicationController
  def select_users
    @course_group = CourseGroup.find modal_params[:course_group_id]
    @students = @course_group.subject.semester.students
    render partial: 'select_users_modal', layout: false
  end

  def update_grades
    @course_group = CourseGroup.find modal_params[:course_group_id]
    @students = @course_group.enrolled_students
    render partial: 'update_grades_modal', layout: false
  end

  def add_students
    @semester = Semester.find modal_params[:semester_id]
    @students = Student.where.not(id: @semester.students.pluck(:id))
    render partial: 'add_students_modal', layout: false
  end

  private

  def modal_params
    params.permit(:course_group_id, :semester_id)
  end
end

app/views/modals/_add_students_modal.html.haml
.modal.fade{'id' => 'add_students', 'tabindex' => '-1', 'role' => 'dialog', 'aria-labelledby' => 'add_students_modal_label'}
  .modal-dialog{'role' => 'document'}
    .modal-content
      = form_tag add_students_field_of_study_semester_path(field_of_study_id: @semester.field_of_study.id, id: @semester.id)
      .modal-header
        %button.close{'type' => 'button', 'data-dismiss' => 'modal'}
          %span{'aria-hidden' => 'true'} ×
        %h4.modal-title#add_students_modal_label= @semester
      .modal-body
        %p= t('.body')
        - if @students.any?
          - @students.each do |student|
            %p
              %span= check_box_tag 'student_ids[]', student.id
              %span= student.name
        - else
          %p= t('.no_students_message')
      .modal-footer
        %button.btn.btn-default{'type' => 'button', 'data-dismiss' => 'modal'}
          = t('.cancel')
        = submit_tag t('.add_students'), class: 'btn btn-primary'

app/views/modals/_select_users_modal.html.haml
.modal.fade{'id' => 'select_users', 'tabindex' => '-1', 'role' => 'dialog', 'aria-labelledby' => 'select_users_modal_label'}
  .modal-dialog{'role' => 'document'}
    .modal-content
      = form_tag registrate_subject_course_group_path(subject_id: @course_group.subject.id, id: @course_group.id)
      .modal-header
        %button.close{'type' => 'button', 'data-dismiss' => 'modal'}
          %span{'aria-hidden' => 'true'} ×
        %h4.modal-title#select_users_modal_label= t('.title')
      .modal-body
        %p= t('.body')
        - @students.each do |student|
          %p
            %span= check_box_tag 'user_ids[]', student.id
            %span= student.name
      .modal-footer
        %button.btn.btn-default{'type' => 'button', 'data-dismiss' => 'modal'}
          = t('.cancel')
        = submit_tag t('.registrate'), class: 'btn btn-primary'

app/views/modals/_update_grades_modal.html.haml
.modal.fade{'id' => 'update_grades', 'tabindex' => '-1', 'role' => 'dialog', 'aria-labelledby' => 'update_grades_modal_label'}
  .modal-dialog{'role' => 'document'}
    .modal-content
      = form_tag update_grades_subject_course_group_path(subject_id: @course_group.subject.id, id: @course_group.id)
      .modal-header
        %button.close{'type' => 'button', 'data-dismiss' => 'modal'}
          %span{'aria-hidden' => 'true'} ×
        %h4.modal-title#update_grades_modal_label.text-center= t('.title')
      .modal-body
        .col-md-8.col-md-offset-2
          %table.table.table-bordered
            %thead
              %tr
                %th= t('.name')
                %th= t('.grade')
            %tbody
              - @students.each do |student|
                - grade = student.grades.find_or_initialize_by(course_group: @course_group)
                = hidden_field_tag "grades[][user_id]", student.id
                %tr
                  %td= student.name
                  %td.form-group
                    = select_tag "grades[][value]", options_for_select(Grade::GRADE_VALUES, grade.value), include_blank: true, class: 'form-control'
      .modal-footer
        .col-md-8.col-md-offset-2.text-center
          %button.btn.btn-default{'type' => 'button', 'data-dismiss' => 'modal'}
            = t('.cancel')
          = submit_tag t('.save'), class: 'btn btn-primary'