config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    resources :course_groups do
      member do
        post 'registrate'
        post 'deregistrate'
        post 'update_grades'
      end
    end
  end
  get 'course_groups/overview' => 'course_groups#overview'

  resources :field_of_studies do
    resources :semesters do
      post 'add_students', on: :member
      delete 'remove_students', on: :member
    end
  end
  resources :registrations

  get 'select_users' => 'modals#select_users', as: :select_users_modal
  get 'update_grades' => 'modals#update_grades', as: :update_grades_modal
  get 'add_students' => 'modals#add_students', as: :add_students_modal

  root 'dashboard#index'
  get 'my_study' => 'users#my_study', as: :my_study_user

  devise_for :users, skip: [:registrations]

  get 'language' => 'languages#change', as: :change_language

  resources :users do
    patch 'update_password', on: :member
  end

  get 'edit_account' => 'users#edit_account'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/views/layouts/_devise_header.html.haml
%header
  .container
    .row
      = yield :warning
      .col-md-2.pull-left
  %nav.navbar.navbar-inverse{role: "navigation"}
    .container
      / Brand and toggle get grouped for better mobile display
      .navbar-header.my-header
        %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      / Collect the nav links, forms, and other content for toggling
      .collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right.user-nav
          = render 'layouts/header_user_menu'

app/views/layouts/_footer.html.haml
%footer
  .footer
    .container
      %p
        = link_to t(".home"), "#", class: "btn btn-link"
        = "|"
        = link_to t(".contact"), "#", class: "btn btn-link"
        = "|"
        = link_to t(".help"), "#", class: "btn btn-link"
        = "|"
        = link_to t(".about"), "#", class: "btn btn-link"
        = other_language_link

app/views/layouts/_footer_links.html.haml
%li
  = link_to "users", new_user_session_path
  = link_to "Kontakt", new_user_session_path
  = link_to "terms", new_user_session_path

app/views/layouts/_header.html.haml
%header
  .container
    .row
      = yield :warning
      .col-md-2.pull-left
  %nav.navbar.navbar-inverse{role: "navigation"}
    / Brand and toggle get grouped for better mobile display
    .navbar-header.my-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    / Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse
      = render 'layouts/header_main_menu'
      %ul.nav.navbar-nav.pull-right.user-nav
        = render 'layouts/header_user_menu'

app/views/layouts/_header_main_menu.html.haml
%ul.nav.navbar-nav.navbar-top-links
  %li= link_to t(".dashboard"), root_path
  %li= link_to t(".field_of_studies"), field_of_studies_path
  %li= link_to t(".subjects"), subjects_path
  - unless current_user.admin?
    %li= link_to t(".my_study"), my_study_user_path
  %li= link_to t(".registrations"), registrations_path
  - if current_user.admin?
    %li= link_to t(".users"), users_path
  %li= link_to t(".settings"), edit_account_path

app/views/layouts/_header_user_menu.html.haml
- if current_user
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
      = current_user.email
      %b.caret
    %ul.dropdown-menu
      %li
        = link_to I18n.t("layouts.header.logout"), destroy_user_session_path, method: :delete
- else
  %li
    = link_to t("layouts.header.login"), new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LICENCJAT
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .wrapper
      = render "layouts/header"
      .container
        = yield
      .push
    = render "layouts/footer"

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LICENCJAT
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .wrapper
      = render "layouts/devise_header"
      .container
        = bootstrap_flash
        = yield
      .push
    = render "layouts/footer"